var r_tip = new Array ();
var i = Math.floor(9*Math.random())
r_tip[0] = "Not to be confused with Hive Pet Care";
r_tip[1] = "Not to be confused with Aperture Science";
r_tip[2] = "Do not name your dog GLaDOS";
r_tip[3] = "Avoid spraying deadly neurotoxins on your gerbil";
r_tip[4] = "DO NOT GIVE A HAMSTER A PORTAL GUN!";
r_tip[5] = "Do not let Headcrabs play with your pets";
r_tip[6] = "We have better customer service than Black Mesa!";
r_tip[7] = "Consider getting a Companion Cube as your next pet";
r_tip[8] = "Try an Aperture Science Counterproductive Canine Distribution Device";
